blank_issues_enabled: false
contact_links:
  - name: OnOffice SDK Documentation
    url: https://github.com/therealJMT/onoffice-python-tools/blob/main/README.md
    about: Check our documentation before creating an issue
  - name: Security Issue
    url: https://github.com/therealJMT/onoffice-python-tools/security/policy
    about: Please report security vulnerabilities directly to the maintainers
